/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_luoye_serialport_SerialPort */

#ifndef _Included_com_demo_SerialPort
#define _Included_com_demo_SerialPort
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jobject JNICALL Java_com_demo_SerialPort_open
  (JNIEnv *, jclass, jstring, jint, jint);


JNIEXPORT void JNICALL Java_com_demo_SerialPort_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
